/**
 * Every IPC channel in the application. The equivalent of a routes file.
 * Adding a channel here and nowhere else will fail to compile — that is intended.
 */
export const channels = {
  sale: {
    create: 'sale:create',
    cancel: 'sale:cancel',
    getById: 'sale:getById',
    listByDate: 'sale:listByDate',
  },
  item: {
    create: 'item:create',
    update: 'item:update',
    search: 'item:search',
    stockOnHand: 'item:stockOnHand',
    lookups: 'item:lookups',
    getPrices: 'item:getPrices',
  },
  party: {
    create: 'party:create',
    search: 'party:search',
    searchAny: 'party:searchAny',
    get: 'party:get',
    ledger: 'party:ledger',
    balance: 'party:balance',
  },
  customer: {
    create: 'customer:create',
    search: 'customer:search',
    get: 'customer:get',
    balance: 'customer:balance',
  },
  staff: {
    create: 'staff:create',
    listStaff: 'staff:listStaff',
    saveAttendance: 'staff:saveAttendance',
    getMonthAttendance: 'staff:getMonthAttendance',
    recordAdvance: 'staff:recordAdvance',
    listAdvances: 'staff:listAdvances',
  },
  expense: {
    create: 'expense:create',
    list: 'expense:list',
    listCategories: 'expense:listCategories',
    listBusinessUnits: 'expense:listBusinessUnits',
  },
  cashSession: {
    open: 'cashSession:open',
    close: 'cashSession:close',
    today: 'cashSession:today',
  },
  purchase: {
    create: 'purchase:create',
    cancel: 'purchase:cancel',
    list: 'purchase:list',
    printOrder: 'purchase:printOrder',
  },
  payment: { receive: 'payment:receive', pay: 'payment:pay' },
  job: {
    create: 'job:create',
    assignTechnician: 'job:assignTechnician',
    transitionStatus: 'job:transitionStatus',
    getById: 'job:getById',
    list: 'job:list',
    issueToJob: 'job:issueToJob',
    listJobParts: 'job:listJobParts',
    deliver: 'job:deliver',
    reconcileCustody: 'job:reconcileCustody',
    getJobSplit: 'job:getJobSplit',
    getTechnicianCustody: 'job:getTechnicianCustody',
    listTechnicians: 'job:listTechnicians',
    listServiceCharges: 'job:listServiceCharges',
  },
  uom: { listConversions: 'uom:listConversions' },
  report: {
    dailySales: 'report:dailySales',
    receivables: 'report:receivables',
    stockValuation: 'report:stockValuation',
    cashBook: 'report:cashBook',
    unitPl: 'report:unitPl',
    wageMonth: 'report:wageMonth',
  },
  importData: {
    dryRun: 'import:dryRun',
    commit: 'import:commit',
    supplierBalanceDryRun: 'import:supplierBalance:dryRun',
    supplierBalanceCommit: 'import:supplierBalance:commit',
    customerBalanceDryRun: 'import:customerBalance:dryRun',
    customerBalanceCommit: 'import:customerBalance:commit',
  },
  backup: { now: 'backup:now', restore: 'backup:restore' },
  setting: {
    getReceiptPaperSize: 'setting:getReceiptPaperSize',
    setReceiptPaperSize: 'setting:setReceiptPaperSize',
    getShopName: 'setting:getShopName',
    setShopName: 'setting:setShopName',
    getDiscountApplyWalkin: 'setting:getDiscountApplyWalkin',
    setDiscountApplyWalkin: 'setting:setDiscountApplyWalkin',
    getDiscountApplyWholesale: 'setting:getDiscountApplyWholesale',
    setDiscountApplyWholesale: 'setting:setDiscountApplyWholesale',
    getDiscountPkrEnabled: 'setting:getDiscountPkrEnabled',
    setDiscountPkrEnabled: 'setting:setDiscountPkrEnabled',
    getDiscountPctEnabled: 'setting:getDiscountPctEnabled',
    setDiscountPctEnabled: 'setting:setDiscountPctEnabled',
    getDiscountPkrPresets: 'setting:getDiscountPkrPresets',
    setDiscountPkrPresets: 'setting:setDiscountPkrPresets',
    getDiscountPctPresets: 'setting:getDiscountPctPresets',
    setDiscountPctPresets: 'setting:setDiscountPctPresets',
    getDiscountConfig: 'setting:getDiscountConfig',
  },
  print: { reprintReceipt: 'print:reprintReceipt' },
  invoice: { printSaleInvoice: 'invoice:printSaleInvoice' },
  system: { ping: 'system:ping' },
} as const;

export type Channel = typeof channels;
